name: Build Unreal Engine Plugin
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: self-hosted
    name: Build Unreal Engine Plugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Package Project
        env: 
          UE_PATH: 'C:\Program Files\Epic Games\UE_5.7' # Path to your Unreal Engine installation
          PROJECT_PATH: 'C:\Users\wistf\Unreal Projects\NightSkyEngine\NightSkyEngine.uproject' # Path to your Unreal project file
          OUTPUT_PATH: 'C:\Users\wistf\Unreal Projects\NightSkyEngine\Build\WindowsEditor' # Path to where you want to store the packaged game
        run: |
          # Try to run empty UAT to check for correct path
          & $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildEditor -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -configuration=Development -archivedirectory="$env:OUTPUT_PATH"

      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: 'C:\Users\wistf\Unreal Projects\NightSkyEngine\Build\WindowsEditor'
          file_path: 'C:\Users\wistf\Unreal Projects\NightSkyEngine\Build\NSEPlugin.zip'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NSEPlugin
          path: 'C:\Users\wistf\Unreal Projects\NightSkyEngine\Build\NSEPlugin.zip'